### ISSUE TITLE
Losses explode when training COMBO with the default hyperparameters

### ISSUE THREAD

**Issue by abenechehab** [sparkmxy/my-offlinerl#1]
Hi guys,

Thanks a lot for the codebase you open-sourced.

I'm trying to build on your implementation of model-based offline algorithms (mainly COMBO) to use it with other types of generative models. During my experiments I observed a  numerical overflow (Losses exploding to infinity after 9-10 epochs of the agent training). Screenshot below.

This occurs in hopper-v2 environment with the d4rl medium dataset for instance.

Here are the hyperparameters:

```
seed = 42 

device = 'cuda'+":"+str(select_free_cuda()) if torch.cuda.is_available() else 'cpu'
obs_shape = None
act_shape = None
max_action = None

hidden_layer_size = 400
hidden_layers = 2
transition_layers = 4

transition_init_num = 7
transition_select_num = 5

real_data_ratio = 0.5

transition_batch_size = 256
policy_batch_size = 256
data_collection_per_epoch = 50e3
buffer_size = 120e4
steps_per_epoch = 1000
max_epoch = 500

learnable_alpha = True
transition_lr = 1e-3
actor_lr = 1e-4
critic_lr = 3e-4
target_entropy = None
discount = 0.99
soft_target_tau = 5e-3

num_samples = 10
learnable_beta = True
base_beta = 1.0
lagrange_thresh = 5
with_important_sampling = True

horizon = 5
```

Command:

`python examples/train_d4rl.py --algo_name=combo --exp_name=d4rl-hopper-medium-combo-1 --task d4rl-hopper-medium-v2`

<img width="400" alt="combo" src="https://user-images.githubusercontent.com/57601315/173360571-e4ccdb17-e0ce-4bb1-a79f-2aa4c80e1df6.PNG">

Have you observed anything like this before? And if it's a matter of hyperparameters can you suggest the best hyperparameters for the hopper-medium experiment for instance?

Thank you,
Regards.

**Comment by sparkmxy** [comment]
Sorry that actually I am not a machine learning expert. I am just an undergraduate student who took the Reinforcement Learning course back then. 😂

This code repository was forked when I was doing the course assignment. Here is the original repository: [OfflineRL](https://github.com/polixir/OfflineRL). You may try to contact the original authors. 

I merely made some optimizations to the MOPO algorithm, and only changed the file offlinerl/algo/modelbase/mopo.py on top of the original repository. 
I strongly recommend you work on the original repository.
And I will change `readme.md` to avoid confusion in the future. 

Hope things work out for you.

**Comment by abenechehab** [comment]
Ah I thought this was the original repo, thanks for your answer Ill try to contact them.
Regards,
